/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './{src,pages,components,app}/**/*.{ts,tsx,js,jsx,html}',
    '!./{src,pages,components,app}/**/*.{stories,spec}.{ts,tsx,js,jsx,html}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
   safelist: [
    'border-blue-500',
    'bg-blue-50',
    'hover:bg-blue-100',
    'text-blue-700',
    'bg-blue-100',
    'text-blue-800',
    'bg-blue-500',
    'bg-blue-600',
    'hover:bg-blue-700',
    'text-blue-600',
    
    'border-green-500',
    'bg-green-50',
    'hover:bg-green-100',
    'text-green-700',
    'bg-green-100',
    'text-green-800',
    'bg-green-500',
    'bg-green-600',
    'hover:bg-green-700',
    'text-green-600',
    
    'border-purple-500',
    'bg-purple-50',
    'hover:bg-purple-100',
    'text-purple-700',
    'bg-purple-100',
    'text-purple-800',
    'bg-purple-500',
    'bg-purple-600',
    'hover:bg-purple-700',
    'text-purple-600',
    
    'border-yellow-500',
    'bg-yellow-50',
    'hover:bg-yellow-100',
    'text-yellow-700',
    'bg-yellow-100',
    'text-yellow-800',
    'bg-yellow-500',
    'bg-yellow-600',
    'hover:bg-yellow-700',
    'text-yellow-600',
  ],
};
