import './global.css';
import { ThemeProvider } from '@multi-tenancy/design-system';
import { tailwindAdapter } from '@multi-tenancy/design-system/adapters/tailwind';

export const metadata = {
  title: 'Welcome to cryptocurrency',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider adapter={tailwindAdapter}>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
