import './global.css';
import { ThemeProvider } from '@multi-tenancy/design-system';
import { tailwindAdapter } from '@multi-tenancy/design-system/adapters/tailwind';

export const metadata = {
  title: 'Welcome to cryptocurrency',
  description: 'Generated by create-nx-workspace',
};

/**
 * Root layout component that wraps page content with the ThemeProvider using the Tailwind adapter.
 *
 * @param children - The React nodes to render inside the ThemeProvider (app content).
 * @returns The top-level HTML structure (`<html lang="en">` with a `<body>`) containing the ThemeProvider-wrapped `children`.
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider adapter={tailwindAdapter}>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}